name: expedientes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  bot_toast: ^4.1.3
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/on_boarding/
  - assets/images/social_media/
  - assets/logos/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 900
        - asset: fonts/Quicksand-Light.ttf
          style: italic
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 700

